### ISSUE TITLE
style for selected node

### ISSUE THREAD

**Issue by opto** [hizzgdev/jsmind#449] opened 2023-04-20 17:42 UTC
the current style for the selected node (background color) is somewhat in conflict with the function jm.set_node_color (bg_color).

I have chosen to use a colored border instead. This way, I can set any background color (if using a black border and no dark mode) and can still see the node and and whether it is selected. If selected, my background color will not be overridden.

In a dark mode, the border should be white.

Maybe that is of general interest.

**Comment by hizzgdev** [comment] 2023-04-21 10:07
So the issue is the conflict between `style` and `set_node_color`?

But sure, jsMind is not supported on `dark mode` well, will take look at it. Thanks for your reporting.

**Comment by opto** [comment] 2023-04-21 20:00
yes, the style gives a bg color to selected, and if I set bg color of nodes to signal a subtopic, then that background color is overridden when selected.

If it is a colored border, the chosen bg color can still be seen and also, that it is selected. I chose black border line because I would not choose black bg color

**Comment by opto** [comment] 2023-04-22 20:45
one more question: why does select node reset the node style, namely color and background color in view.select_node -> clear_node_custom_style?

by intention or bug?

The result is:

I select a node, set text color, e.g. red
I unselect it, it is red
I select it, it goes to black
I unselect it, it goes to red.

Shouldn't it stay at red, even if selected?

**Comment by hizzgdev** [comment] 2023-04-24 08:58
Would you like to try the ES6 version?  The issue has been fixed by https://github.com/hizzgdev/jsmind/pull/406, but just for ES6 version.

**Closed** 2023-05-20 17:11 UTC
