### ISSUE TITLE
Dragging nodes should scroll if needed

### ISSUE THREAD

**Issue by lborgman** [hizzgdev/jsmind#433] opened 2023-04-06 01:19 UTC
Currently dragging a node does not scroll the inner of "jsmind_container" if a node is dragged to the border. I do not really understand the implementation of dragging here, but I believe the dragging built into the DOM might work better. Please see this link:

https://stackoverflow.com/questions/71206691/page-does-not-scroll-up-when-dragging-an-element-to-top-with-fixed-navigation-ba

**Comment by hizzgdev** [comment] 2023-04-06 07:34
So, It's a BIG mindmap, and we need to drag a node to a distant parent node?

**Comment by lborgman** [comment] 2023-04-06 10:51
No, the mindmap is probably not very big, but mobile screens are small. (I am just working on some small changes on jsmind.draggable-node.js for this. Please see the mail I sent you.)

**Comment by hizzgdev** [comment] 2023-04-06 11:56
So the problem is It's hard to drag-and-drop a node on a mobile device? I believe it is really not easy.

But I think it probably should NOT be a question. In my opinion, we should not expect it to have the same user experience on both BIG screen and SMALL screen. In other words, it should be two different products on mobile and on web, especially for the non read-only product.

Alright, Alright, let me tell you the truth, I haven't optimized this feature for mobile devices. I think you would better to change it for your case, and all the pull-requests are welcome. Thanks. :rofl:

**Comment by lborgman** [comment] 2023-04-06 16:49
It is easy with the drag-and-drop built into html5.

**Comment by qrdlgit** [comment] 2023-04-18 18:10
Looks easily fixed with 

```
  jdom.add_event(container, 'mousemove', function (e) {
                var evt = e || event;
                jd.drag.call(jd, evt);
                var el = evt.target || evt.srcElement;
                el.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: "nearest"  }); //Just add this line
            });
```

**Comment by qrdlgit** [comment] 2023-04-19 00:25
> > Looks easily fixed with
> > ```
> >   jdom.add_event(container, 'mousemove', function (e) {
> >                 var evt = e || event;
> >                 jd.drag.call(jd, evt);
> >                 var el = evt.target || evt.srcElement;
> >                 el.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: "nearest"  }); //Just add this line
> >             });
> > ```
> 
> Nice and simple. But unfortunately to simple. 🤨 The nodes you want might be totally outside of the visible view.

Works for me, but haven't tested on iphone.

**Closed** 2023-05-20 15:57 UTC
