### ISSUE TITLE
Nodes don't move when press up/down keys

### ISSUE THREAD

**Issue by miyaz** [hizzgdev/jsmind#584] opened 2024-03-13 01:01 UTC
Hi, 
Thanks for developing great software.
I've found a behavior that seems to be a bug, so I'll report it.

When moving a node selection using the up/down keys, I can see a behavior that move to two nodes ahead or don't move.

Reproduction steps: 
* Create multiple nodes under same parent[1]
* Move one of them to another parent[2]
* Select any node from which to move and move with the up/down keys[3]

[1]
![1](https://github.com/hizzgdev/jsmind/assets/7643469/e9a77317-75b6-4f1f-a472-413c3c29b934)
[2]
![2](https://github.com/hizzgdev/jsmind/assets/7643469/82516c18-5c4b-47b3-b9d7-f8609ed1e0df)
[3]
![3](https://github.com/hizzgdev/jsmind/assets/7643469/72ec747a-6a16-43c7-933f-4332599b509a)

**Comment by hizzgdev** [comment] 2024-03-14 03:05
hi @miyaz , do you use the latest version of jsmind, seems the issue is fixed in [v0.7.9](https://github.com/hizzgdev/jsmind/releases/tag/v0.7.9), can you take a look at the version of jsmind in your project?

**Comment by miyaz** [comment] 2024-03-14 03:12
I use v0.8.1.
I've confirmed that it also occurs with the latest version (0.8.2) on the page below.
https://hizzgdev.github.io/jsmind/example/2_features.html

**Comment by hizzgdev** [comment] 2024-03-14 03:21
issue confirmed, will fix it ASAP. Thanks @miyaz

**Closed** 2024-03-14 04:15 UTC

**Comment by hizzgdev** [comment] 2024-03-14 10:34
The update has been released in https://github.com/hizzgdev/jsmind/releases/tag/v0.8.3 
Thanks again @miyaz
